<?php
session_start();

/* IMPORTANT: Disable all output/errors for PDF */
error_reporting(0);
ini_set('display_errors', 0);

require_once 'config.php';
require_once 'fpdf/fpdf.php';

/* ===============================
   SECURITY CHECK
   =============================== */
if (!isset($_SESSION['role']) || $_SESSION['role'] !== 'student') {
    die("Unauthorized access");
}

if (!isset($_GET['quiz_id'])) {
    die("Quiz ID missing");
}

$student_id = $_SESSION['user_id'];
$quiz_id    = (int) $_GET['quiz_id'];

/* ===============================
   FETCH STUDENT NAME
   =============================== */
$studentRes = mysqli_query($conn, "
    SELECT name 
    FROM Students 
    WHERE id = $student_id 
    LIMIT 1
");
$studentRow  = mysqli_fetch_assoc($studentRes);
$student_name = $studentRow['name'] ?? 'Student';

/* ===============================
   FETCH QUIZ TITLE AND CREATED DATE
   =============================== */
$quizRes = mysqli_query($conn, "
    SELECT title, created_at
    FROM quizzes 
    WHERE id = $quiz_id 
    LIMIT 1
");
$quizRow   = mysqli_fetch_assoc($quizRes);
$quiz_title = $quizRow['title'] ?? 'Quiz';
$quiz_created_at = $quizRow['created_at'] ?? date('Y-m-d H:i:s');

/* ===============================
   GET ATTEMPT ID (SUBMITTED ONLY)
   =============================== */
$attemptRes = mysqli_query($conn, "
    SELECT id
    FROM quiz_attempts
    WHERE quiz_id = $quiz_id
    AND student_id = $student_id
    AND status = 'submitted'
    LIMIT 1
");

if (mysqli_num_rows($attemptRes) === 0) {
    die("Quiz not submitted yet");
}

$attemptRow = mysqli_fetch_assoc($attemptRes);
$attempt_id = (int) $attemptRow['id'];

/* ===============================
   FETCH ANSWER KEY (OBJECTIVE ONLY)
   =============================== */
$query = "
SELECT
    q.question_text,
    q.marks,
    q.answer_explanation,
    sa.selected_answer,
    qa.correct_answer
FROM student_answers sa
JOIN questions q
    ON q.id = sa.question_id
JOIN question_answers qa
    ON qa.question_id = q.id
WHERE sa.attempt_id = $attempt_id
AND q.question_type != 'descriptive'
";

$result = mysqli_query($conn, $query);

if (mysqli_num_rows($result) === 0) {
    die("No objective questions found");
}

/* ===============================
   GENERATE PROFESSIONAL PDF
   =============================== */
$pdf = new FPDF();
$pdf->AddPage();

/* ===== TITLE ===== */
$pdf->SetFont('Arial', 'B', 18);
$pdf->SetTextColor(90, 14, 36); // maroon
$pdf->Cell(0, 12, 'ANSWER KEY', 0, 1, 'C');

$pdf->Ln(2);
$pdf->SetDrawColor(90, 14, 36);
$pdf->Line(10, $pdf->GetY(), 200, $pdf->GetY());
$pdf->Ln(8);

/* ===== STUDENT / QUIZ INFO ===== */
$pdf->SetFont('Arial', '', 11);
$pdf->SetTextColor(0, 0, 0);

$pdf->Cell(40, 8, 'Student Name:', 0, 0);
$pdf->Cell(0, 8, $student_name, 0, 1);

$pdf->Cell(40, 8, 'Quiz Title:', 0, 0);
$pdf->Cell(0, 8, $quiz_title, 0, 1);

$pdf->Cell(40, 8, 'Created On:', 0, 0);
$pdf->Cell(0, 8, date('d M Y, h:i A', strtotime($quiz_created_at)), 0, 1);

$pdf->Ln(6);

/* ===== QUESTIONS ===== */
$qno = 1;

while ($row = mysqli_fetch_assoc($result)) {

    // Question box
    $pdf->SetFillColor(245, 245, 245);
    $pdf->SetFont('Arial', 'B', 11);
    $pdf->MultiCell(0, 9, "Q$qno. {$row['question_text']}", 0, 'L', true);

    $pdf->Ln(1);

    $pdf->SetFont('Arial', '', 11);

    // Your Answer
    $pdf->Cell(45, 8, 'Your Answer:', 0, 0);
    $pdf->Cell(0, 8, $row['selected_answer'], 0, 1);

    // Correct Answer
    $pdf->Cell(45, 8, 'Correct Answer:', 0, 0);
    $pdf->Cell(0, 8, $row['correct_answer'], 0, 1);

    // Explanation (if exists)
    if (!empty($row['answer_explanation'])) {
        $pdf->Cell(45, 8, 'Explanation:', 0, 1);
        $pdf->MultiCell(0, 8, $row['answer_explanation']);
    }

    // Marks
    $pdf->Cell(45, 8, 'Marks:', 0, 0);
    $pdf->Cell(0, 8, $row['marks'], 0, 1);
    // Separator
    $pdf->Ln(4);
    $pdf->SetDrawColor(200, 200, 200);
    $pdf->Line(10, $pdf->GetY(), 200, $pdf->GetY());
    $pdf->Ln(6);

    $qno++;
}

/* ===== FOOTER ===== */
$pdf->SetY(-15);
$pdf->SetFont('Arial', 'I', 9);
$pdf->SetTextColor(120, 120, 120);
$pdf->Cell(0, 10, 'Generated by QuizLance', 0, 0, 'C');

/* DOWNLOAD */
$pdf->Output('D', 'Answer_Key.pdf');
exit;
